'use client';
import { toBlob, toPng } from 'html-to-image';
import { Download, Share2, Sparkles, Sticker } from 'lucide-react';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import styles from './brat-studio.module.css';

type ThemeId='green'|'white'|'strike'|'mirror'|'random';
type Theme={id:ThemeId;label:string;background:string;textColor:string;inputDefault:string;mirrored?:boolean;strike?:boolean;animated?:boolean;blur?:number};
const THEMES:Theme[]=[{id:'green',label:'Brat Green',background:'#8ace00',textColor:'#101010',inputDefault:'brat',blur:1.15},{id:'white',label:'White',background:'#ffffff',textColor:'#111111',inputDefault:"brat and it's still brat",blur:.6},{id:'strike',label:'Strike',background:'#8ace00',textColor:'#111111',inputDefault:'brat',strike:true,blur:1.1},{id:'mirror',label:'Mirror',background:'#8ace00',textColor:'#111111',inputDefault:"brat and it's completely different but also still brat",mirrored:true,blur:1},{id:'random',label:'Random Video',background:'#0f0f0f',textColor:'#f5f5f5',inputDefault:'the moment',animated:true,blur:0}];
const RANDOM_SCENES=[{bg:'#0000ff',text:'#00ff00'},{bg:'#000000',text:'#ffffff'},{bg:'#ff0000',text:'#0a00ad'},{bg:'#00ff00',text:'#111111'},{bg:'#ffdf00',text:'#0000ff'},{bg:'#111111',text:'#ff4ed8'}];
function downloadBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function wrapText(value:string,maxLineLength=12){const words=value.trim().split(/\s+/).filter(Boolean);if(!words.length)return['brat'];const lines:string[]=[];let current='';for(const word of words){const next=current?`${current} ${word}`:word;if(next.length<=maxLineLength||current.length===0){current=next}else{lines.push(current);current=word}}if(current)lines.push(current);return lines.slice(0,5)}
async function blobToFile(blob:Blob,filename:string){return new File([blob],filename,{type:blob.type||'application/octet-stream'})}
export function BratStudio(){const [themeId,setThemeId]=useState<ThemeId>('green');const [text,setText]=useState('brat');const [hd,setHd]=useState(true);const [busy,setBusy]=useState<'png'|'video'|'share'|null>(null);const [shareHint,setShareHint]=useState('');const cardRef=useRef<HTMLDivElement>(null);const theme=useMemo(()=>THEMES.find(i=>i.id===themeId)??THEMES[0],[themeId]);useEffect(()=>{setText(theme.inputDefault)},[theme.inputDefault]);const lines=useMemo(()=>wrapText(text,themeId==='green'?9:themeId==='random'?10:15),[text,themeId]);const exportScale=hd?3:2;
const exportPng=useCallback(async()=>{if(!cardRef.current)return;setBusy('png');setShareHint('');try{const dataUrl=await toPng(cardRef.current,{cacheBust:true,pixelRatio:exportScale,canvasWidth:1024*exportScale,canvasHeight:1024*exportScale});const res=await fetch(dataUrl);downloadBlob(await res.blob(),`brat-${themeId}.png`)}finally{setBusy(null)}},[exportScale,themeId]);
const renderAnimatedVideo=useCallback(async()=>{const canvas=document.createElement('canvas');const size=hd?1024:768;canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas context unavailable');const stream=canvas.captureStream(12);const recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9'});const chunks:BlobPart[]=[];recorder.ondataavailable=e=>{if(e.data.size>0)chunks.push(e.data)};const finished=new Promise<Blob>(resolve=>{recorder.onstop=()=>resolve(new Blob(chunks,{type:'video/webm'}))});let frame=0;const totalFrames=36;const fps=12;const draw=()=>{const scene=RANDOM_SCENES[frame%RANDOM_SCENES.length];ctx.fillStyle=scene.bg;ctx.fillRect(0,0,size,size);ctx.save();ctx.fillStyle=scene.text;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`900 ${Math.floor(size*.24)}px Impact, Haettenschweiler, Arial`;const ls=wrapText(text.toUpperCase(),9);const baseY=size/2-((ls.length-1)*size*.09)/2;ls.forEach((line,index)=>ctx.fillText(line,size/2,baseY+index*size*.09));ctx.restore();frame+=1};recorder.start();for(let i=0;i<totalFrames;i+=1){draw();await new Promise(r=>setTimeout(r,1000/fps))}recorder.stop();return finished},[hd,text]);
const exportVideo=useCallback(async()=>{setBusy('video');setShareHint('');try{downloadBlob(await renderAnimatedVideo(),'brat-random.webm')}finally{setBusy(null)}},[renderAnimatedVideo]);
const shareToWhatsApp=useCallback(async()=>{setBusy('share');setShareHint('');try{if(theme.animated){const videoBlob=await renderAnimatedVideo();const file=await blobToFile(videoBlob,'brat-random.webm');if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Brat video',text:'Share this to WhatsApp and turn it into a sticker from your phone.'});setShareHint('Share sheet dibuka. Pilih WhatsApp jika device kamu mendukung file sharing.')}else{downloadBlob(videoBlob,'brat-random.webm');setShareHint('Browser ini tidak mendukung share file langsung. File sudah diunduh agar bisa dikirim manual ke WhatsApp.')}return}if(!cardRef.current)return;const blob=await toBlob(cardRef.current,{cacheBust:true,pixelRatio:exportScale,canvasWidth:1024*exportScale,canvasHeight:1024*exportScale});if(!blob)throw new Error('Failed to export image');const file=await blobToFile(blob,`brat-${themeId}.png`);if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Brat sticker',text:'Share this image to WhatsApp. On mobile, you can turn it into a sticker from WhatsApp or a sticker app.'});setShareHint('Share sheet dibuka. Pilih WhatsApp untuk lanjut dari device yang support.')}else{downloadBlob(blob,`brat-${themeId}.png`);window.open(`https://wa.me/?text=${encodeURIComponent('Sticker kamu sudah jadi. Upload PNG yang baru diunduh ke WhatsApp atau app pembuat sticker.')}`,'_blank','noopener,noreferrer');setShareHint('Browser ini belum bisa share file langsung, jadi PNG diunduh dan WhatsApp dibuka sebagai fallback.')}}finally{setBusy(null)}},[exportScale,renderAnimatedVideo,theme.animated,themeId]);
return <main className={styles.page}><section className={styles.shell}><div><div className={styles.hero}><p className={styles.eyebrow}>Next.js + Vercel ready</p><h1>Brat-inspired sticker generator</h1><p className={styles.subcopy}>Clean UI, brat-style modes, HD export, PNG for sticker flow, and animated random mode as WebM.</p></div><div className={styles.panel}><label className={styles.label} htmlFor="brat-text">Text</label><input id="brat-text" className={styles.input} maxLength={theme.animated?30:themeId==='green'?20:70} value={text} onChange={e=>setText(e.target.value)} placeholder="Type something"/><div className={styles.toolbarRow}><div><p className={styles.label}>Mode</p><div className={styles.themeGrid}>{THEMES.map(item=><button key={item.id} type="button" className={`${styles.themeButton} ${item.id===themeId?styles.activeTheme:''}`} onClick={()=>setThemeId(item.id)}><span className={styles.swatch} style={{background:item.animated?'linear-gradient(135deg, #0000ff, #ff0000, #00ff00)':item.background}} />{item.label}</button>)}</div></div><label className={styles.hdToggle}><input type="checkbox" checked={hd} onChange={e=>setHd(e.target.checked)} /><span>Brat HD</span></label></div><div className={styles.actions}><button type="button" className={styles.primary} onClick={theme.animated?exportVideo:exportPng} disabled={busy!==null}>{theme.animated?<Sparkles size={18}/>:<Download size={18}/>} {busy==='video'||busy==='png'?'Generating…':theme.animated?'Export WebM':'Download PNG'}</button><button type="button" className={styles.secondary} onClick={shareToWhatsApp} disabled={busy!==null}><Sticker size={18}/> {busy==='share'?'Preparing…':'Share to WhatsApp'}</button></div><p className={styles.note}>WhatsApp dari browser tidak bisa langsung menambahkan file ke tray sticker secara otomatis. Flow paling dekat adalah export/share file, lalu lanjutkan dari WhatsApp di perangkat yang support.</p>{shareHint?<p className={styles.shareHint}><Share2 size={16}/> {shareHint}</p>:null}</div></div><div className={styles.previewPane}><div className={styles.previewFrame}><div ref={cardRef} className={`${styles.card} ${theme.animated?styles.cardAnimated:''}`} style={{background:theme.animated?undefined:theme.background,color:theme.textColor}}>{theme.animated?<div className={styles.animatedBackground} aria-hidden="true"/>:null}<div className={`${styles.cardText} ${theme.mirrored?styles.mirrored:''} ${theme.animated?styles.randomText:''}`} style={{filter:`blur(${theme.blur??0}px)`}}>{lines.map(line=><span key={`${line}-${themeId}`}>{theme.animated?line.toUpperCase():line}</span>)}</div>{theme.strike?<div className={styles.strikeScribble} aria-hidden="true"/>:null}<div className={styles.exportBadge}>{hd?'HD':'STD'}</div></div></div><div className={styles.caption}><span>Preview</span><strong>{theme.animated?text.toUpperCase():text}</strong></div></div></section></main>}
